import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core"
import { Provider } from "./AppProvider"
import '@mantine/core/styles.css'
import { getCookies } from "cookies-next"
import { cookies } from "next/headers"
import { CookieServerProvider } from "./CookieProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" {...mantineHtmlProps}>
      <head>

        <ColorSchemeScript />
      </head>
      <body>
        <CookieServerProvider>
          <Provider>
            {children}
          </Provider>
        </CookieServerProvider>
      </body>
    </html>
  )
}

export const fetchCache = 'default-no-store'
export const dynamic = 'force-dynamic'
